server:
  port: 8000
  servlet:
    context-path: /msvc-liga

spring:
  application:
    name: msvc-liga
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      database: app_fubol_dev
      host: ec2-3-85-108-239.compute-1.amazonaws.com
      port: 27017

msvcliga:
  app:
    origin: http://ec2-3-85-108-239.compute-1.amazonaws.com:9000