server:
  port: 8000
  servlet:
    context-path: /msvc-liga

spring:
  application:
    name: msvc-liga
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      database: app_fubol_dev
      host: localhost
      port: 27017
